# Generated by Django 5.0.7 on 2024-07-29 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_rename_booking_date_booking_reservation_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['price']},
        ),
    ]
